version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "Pre-build phase... Setting up necessary dependencies..."
  build:
    commands:
      - echo "Build phase... Preparing Greengrass components..."
      - ls -l
      - cd components
      - >
        for dir in */ ; do
          COMPONENT_NAME="${dir%/}"
          echo "Zipping and uploading $COMPONENT_NAME..."
          zip -r "${COMPONENT_NAME}.zip" "$dir"
          aws s3 cp "${COMPONENT_NAME}.zip" "s3://$BUCKET_NAME/$COMPONENT_NAME/${COMPONENT_NAME}.zip"
          RECIPE=$(jq -c . "$dir/recipes/recipe.json")
          echo "$RECIPE"
          aws lambda invoke --function-name $UPDATE_LAMBDA_FUNCTION_NAME --payload "{ \"componentName\": \"$COMPONENT_NAME\", \"recipe\": $RECIPE }" response_${COMPONENT_NAME}.json
        done
  post_build:
    commands:
      - echo "Post-build phase... Completed."

artifacts:
  discard-paths: yes
