version: 0.2

phases:
  build:
    commands:
      - echo "Zipping repository contents"
      - zip -r myRepo.zip .
      - echo "Uploading to S3"
      - aws s3 cp myRepo.zip s3://$BUCKET_NAME/myRepo.zip