version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo "Pre-build phase... Setting up necessary dependencies..."
  build:
    commands:
      - echo "Build phase... Preparing Greengrass components..."
      - ls -l
      - cd components
      - >
        for dir in */ ; do
          COMPONENT_NAME="${dir%/}"
          echo "Zipping and uploading $COMPONENT_NAME..."
          zip -r "${COMPONENT_NAME}.zip" "$dir"
          aws s3 cp "${COMPONENT_NAME}.zip" "s3://$BUCKET_NAME/$COMPONENT_NAME/${COMPONENT_NAME}.zip"
        done
  post_build:
    commands:
      - echo "Post-build phase... Triggering Lambda function for each component..."
      - >
        for dir in */ ; do
          COMPONENT_NAME="${dir%/}"
          aws lambda invoke --function-name $UPDATE_LAMBDA_FUNCTION_NAME --payload "{ \"component\": \"$COMPONENT_NAME\" }" response_${COMPONENT_NAME}.json
        done

artifacts:
  files:
    - '*.zip'
